project:
  type: website
  output-dir: ../docs/

website:
  title: "crumplab"
  google-analytics: G-HPGGT4QZ8Q
  twitter-card: true
  open-graph: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - People.qmd
      - href: Publications.qmd
        text: Pubs
      - Books.qmd
      - Courses.qmd
      - Apps.qmd
      - Opportunities.qmd
      - Blog.qmd
      - Fun.qmd
    right:
      - icon: github
        href: https://github.com/CrumpLab
        aria-label: GitHub
      - icon: twitter
        href: https://twitter.com/MattCrumpLab
        aria-label: Twitter
      - icon: youtube
        href: https://www.youtube.com/c/CrumpsComputationalCognitionLab
        aria-label: Youtube

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

