---
title: "About Me"
output: 
  html_document:
    includes:
       in_header: g_analytics.html
---

Last updated: 11/28/2021

--------

### Previous Experience

#### Educational Background

- [State Key Laboratory of Cognitive Neuroscience and Learning & IDG/McGovern Institute for Brain Research](http://imibr.bnu.edu.cn/), [Beijing Normal University](https://english.bnu.edu.cn/) (2021-2024), Master student in Cognitive Neuroscience

- [School of Psychology](http://psy.nenu.edu.cn/English/ywsy.htm), [Northeast Normal University](https://en.nenu.edu.cn/) (2017-2021), Undergraduate student in Psychology

#### Research Experience

1. Fractionating Human Intelligence _2020.10 to 2024.6_`Master Student Researcher`

    - Converting traditional cognitive tasks into interesting online games, and using the developed game system (containing over **60** cognitive games) to collect big behavioural data over a sample size over **1,000** adults.
    - Developing cognitive tasks for fMRI tests using Psychtoolbox, and conduct experiment with 30 adults play over 40 cognitive games covering various spects of previous defined cognitve aspects
    - Using factor analysis, machine learning and cognitive models to analyze the behavioural and fMRI data acquired during the previous process

1. Efficincy of Executve Functions Training _2018.9 to 2022.5_`Project Leader`

    - Conducting executive functions training in various way, including VR game, video game, dance training on different target participants including kindergarten children, middle school students, and healthy adults.
    - Combining behavioural data, fNIRS data, and meta-analysis to investigate approaches for improving executive functions training benefits

#### Research Skills

| Skill | Tool Name |
|:--------|-------:|
|Programming| R, Python, Matlab|
|Neuroimaging| fMRI, fNIRS, EEG, MEG|
|Computational Models| Drift Difusion Model, Bayesian Model|
|Advanced Statistics| Factor analysis, Machine learning, Deep learning, Meta-analysis|
|Language | Chinese, English|


