---
title: "Apps"
output: 
  html_document:
    toc: true
    toc_float: true
    collapsed: false
    number_sections: false
    toc_depth: 4
    includes:
       in_header: [g_analytics.html,header_pubs.html]
    css: front.css
---

Shiny Apps, R packages, and various things

---

## R Packages

----

#### [conflictPower](https://crumplab.github.io/conflictPower/)

Monte-carlo based power analysis for cognitive control designs. [https://crumplab.github.io/conflictPower/](https://crumplab.github.io/conflictPower/)

-----

#### [crumplabr](https://github.com/CrumpLab/crumplabr)

A few functions used around the lab. Contains functions for the Van Selst and Jolicoeur outlier procedure. [https://github.com/CrumpLab/crumplabr](https://github.com/CrumpLab/crumplabr).

-----

## Shiny Apps

-----

#### [Semantic librarian](https://crumplab.shinyapps.io/SemanticLibrarian/)

A semantic search engine for the APA abstract database (most of the Experimental journals from 1890s to 2016), formerly known as ATHENA.

We (Harinder Aujla, Randy Jamieson, and Matthew Crump) use semantic vectors from BEAGLE (Jones & Mewhort, 2007) to compute the similarity between abstracts, and authors, and authors and abstracts.

- [https://crumplab.shinyapps.io/SemanticLibrarian/](https://crumplab.shinyapps.io/SemanticLibrarian/)
- source code: [https://github.com/CrumpLab/SemanticLibrarian](https://github.com/CrumpLab/SemanticLibrarian)
- Open science framework project: [https://osf.io/wfcmg/](https://osf.io/wfcmg/)
- Publication: currently under review at Behavioral Research Methods.

-----

#### [hypothesis_explorer](hypothesis_explorer)

A Shiny App for viewing annotations from the Hypothes.is database. Need to download and run locally.

[https://github.com/CrumpLab/hypothesis_explorer](https://github.com/CrumpLab/hypothesis_explorer)

-----

#### [indTtest](https://crumplab.shinyapps.io/indTtest/)

An independent samples t-test simulator.

[https://crumplab.shinyapps.io/indTtest/](https://crumplab.shinyapps.io/indTtest/)

-----

#### [pairedTtest](https://crumplab.shinyapps.io/pairedTtest/)

An paired samples t-test simulator.

[https://crumplab.shinyapps.io/pairedTtest/](https://crumplab.shinyapps.io/pairedTtest/)

-----

#### [simpleexperimentsim](https://crumplab.shinyapps.io/simpleexperimentsim/)

A simple experiment simulator with monte-carlo power analysis

[https://crumplab.shinyapps.io/simpleexperimentsim/](https://crumplab.shinyapps.io/simpleexperimentsim/)


-----

## R Markdown templates

-----

#### [NSFrmarkdown](https://github.com/CrumpLab/NSFrmarkdown)

An R markdown template for NSF grants

[https://github.com/CrumpLab/NSFrmarkdown](https://github.com/CrumpLab/NSFrmarkdown)

-----

#### [LabJournalWebsite](https://github.com/CrumpLab/LabJournalWebsite)

[https://github.com/CrumpLab/LabJournalWebsite](https://github.com/CrumpLab/LabJournalWebsite)

Simple template for an R Markdown Website

-----

#### [rmpatternlanguage](https://github.com/CrumpLab/rmpatternlanguage)

A bookdown theme reproducing the style of "A Pattern Language".

[https://github.com/CrumpLab/rmpatternlanguage](https://github.com/CrumpLab/rmpatternlanguage)


-----







