---
title: "Advocating to hire in black psychology in my department"
author: "Matt Crump"
date: "Last edited: `r format(Sys.time(), '%d %B, %Y')`"
twitter:
  card_description: "Some reflections on hiring and notes on what I can do to advocate for hiring a black psychologist in my department. More work in progress."
  card_img: "https://crumplab.github.io/blogposts/7_1_20_hiring/hiring.png"
bibliography: refs.bib
csl: web/apa.csl
output: 
  html_document:
    template: web/template.html
    toc: true
    toc_float: true
    collapsed: false
    number_sections: false
    toc_depth: 4
    theme: yeti
    highlight: kate
    css: web/crump_basic.css
    includes:
      in_header: web/header.html
    md_extensions: -autolink_bare_uris
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

---

NOTE: I'm writing this partly for myself, but also sharing in case other people find it useful, or find that they can help me be a better advocate, because I'm new at this.

## Some general thoughts

I'm writing this post to organize how I can go about advocating for our department to hire a black psychologist. Specifically, an expert in black psychology, a black psychologist. So, I plan to make a to do list, and then do those things. 

I've been at Brooklyn College since 2011, and I've engaged with the hiring process in lots of different ways. I'm not going to get into the pecularities of our hiring process, which can be a moving target, and which, in my opinion, leaves much to be desired. I've spent time and advocated for change in the process itself, and have not found that investment very fruitful. Instead, at least this time, I'm going to think about how I work within the process to be an advocate.

Our department and Brooklyn College have an important mission that includes celebrating diversity among our student body and faculty. One of the reasons I like my department is because we have a diversity of psychologists, both in terms of their ethnicities and domains of inquiry. And, since 2011, there has been increased efforts to make sure our hiring process is equitable, open, and connects us with diverse candidates. I've sat in trainings, and meetings, and so on, trying to reflect and brainstorm ways to improve the hiring process. Nevertheless, even though we've made about 13 new hires since I arrived, we haven't hired a black psychologist. We have hired non-white psychologists. Right now we have about 34 faculty, and 1 black psychologist. Our students are more diverse than our faculty.

It seems like we're trying to change, but actually moving forward with increasing the diversity of our faculty is not happening very quickly. I can speculate on reasons why, but I'd rather get to my to do list.

But, before I do that, I should say in general what we normally do when hiring. First, there is a process for figuring out what "area" in psychology we want to hire in. Second, a small committee writes up specific line requests to the administration. If the administration approves the lines, we make search committees, conduct searches etc. I've participated in basically all of these things over time.

Previously I have primarily advocated for hiring in my own area (Cognition), but also other areas. Taking my own area, it is small (at BC), and in general cognition isn't very diverse. I'm a member of Psychonomics, which is very white. Cognition in general and in my department needs more diversity. Cognition is not alone. My impression is that many other domains in psychology are very white and not diverse. 

As a side-note, I'm reflecting a bit on my own thinking about diversifying our department. One issue I know I've thought about is about where to put my support in advocating for lines. For example, there have been times when I wrote in support of a cognitive line, but did not write in support of a so-called diversity domain line. 

Occasionally, we discuss hiring in the domain of diversity research. Part of the motivation appears to be that diversity researchers may be more ethnically diverse, so a line on that topic would have a better chance of attracting a more diverse group of applicants and candidates.

I know that I have a complicated reaction to this one contrast between hiring in cognition versus diversity. And, of course, I've set this as the contrast to help myself talk to myself to sort it out. So, what's the problem MATT, why don't you what to hire someone who studies diversity issues?

Well, there's a bunch of things saddling my thinking about this. I think some of it is borne out of department politics and resources. And, some of it is comes from my own biases and interests. For example, although creating a line for someone who studies diversity issues could lead to hiring a diverse candidate, it may not. Also, we can't become complacent and somehow avoid the problem of diversifying the more "traditional" domains in our department. So, it's a bigger problem. My opinion is that we can't solve all of our diversity issues by only hiring faculty who study diversity issues.

Another general issue for any new line relates to existing groupings within the department and how resources are assigned to the different groups. Our department is resource stressed in lots of ways, and also super grouped in really strange ways. My impression is that everyone is pretty friendly overall, which is good. Nevertheless, the give and take and protect your resources at all cost is a thing. Certainly, the fear or threat is palpable. So, for example, one grouping of psychologists can squeeze out another grouping by controlling access to resources. All groups find ways to get resources. Everyone is concerned about introducing "new groups", who will obviously take away resources from other groups. I keep hearing that resources don't grow on trees. I've also watched the cognition program be drained and not replenished, while other areas grow. But, every area has their own story of woe, and how they need more resources.

OK, I think I've done enough rambling. Our department needs to diversify its faculty period, and across the board in all of our domains. If we want to make a home for faculty in research areas that are new to our department, we need to invite them into a department that is prepared to make them a success. 

One last thing as a very weak analogy about structural racism. As a white person I'm oblivious to the many structures of racism, and I'm trying to unobliviate myself to the extent that is even possible. So, I'm thinking about what the institution did for me, and what it didn't do, and now that I'm apart of one, what I need to make it do for the next person.

Here's two things. One, I'm a cognitive psychologist, and I didn't have to create a course proposal to have Cognitive Psychology on the books when I arrived to teach. Turns out I don't really teach my topic very often, and teach mostly stats or research methods. But, I didn't have to write course proposals for those either. Why is this important? I've already done my homework. We don't have any courses that cover Black Psychology. I didn't have to write course proposals for my own courses straight away when I arrived (e.g., just to get them listed in the bulletin). Neither should my new colleagues. A door like this needs to be cut open beforehand.

Two, our department can do better for new faculty. I've seen some improvements already. I had major space issues when I started. Specifically, not having any. After a series of events I now have space. I've been vocal about how much this sucked for me and colleagues in a similar position who joined at the same time I did. We've hired several people, and I saw our department step up and help prepare space for them, more than for me. Which makes me happy, because we are headed in the right direction (it's still a problem though). Still, there's little details that institutions suck at. For example, my institution has never bothered to print a label of my name for my office door. They did it for everyone else. They didn't do it for my first office, or to my second office when I moved. This is a trivial bullshit first-world professor problem I know. It's just that now that I think about this, I need to make sure my department is on the ball with printing these things so they don't forget our new hires. Bottom line, we need to make space, and have that space be somewhere worth wanting to be. This includes office door labels for everyone before they arrive, and more important things, mainly more important things.

## Things to do

I've recently discovered the Journal of Black Psychology, and started reading it from the beginning (circa 1974). I have a long way to go. @williamsHistoryAssociationBlack1974 gives a brief history about the formation of the journal and [The Association of Black Psychologists](http://www.abpsi.org). Fast forwarding a bunch of years, @cokleySpeakingTruthPower2018 reviews 50 years of research in the domain of Black Psychology. I've been reading and reading, and this is some of the best work I've ever seen in any psychology. Apart from this little chapter in my blog, I intend to keep reading and probably use this blog to reflect on what I'm learning.

The thing is, I've already learned enough to know that I'm going change the direction of my advocacy for hiring in our department. I need to advocate for hiring in the domain of black psychology. There are lots of reasons why. We have a department that prides itself in having an array of interests, rather than a department that builds strength in one or two areas. And, we talk about hiring "synergistically", looking for people that connect emerging areas with existing areas in our department. I can appreciate some of the idealism. Our department needs the soul of black psychology. My hope is that we can be good and deserving enough of that soul.

I am very ashamed that I did not know about Black Psychology. For me, it would be like not knowing about Cognitive Psychology. For example, if another psychologist professed to be a psychologist and told me they had never heard of cognitive psychology, I would feel puzzled, even astonished...how could you not... Sure, Cognitive Psychology has been around a bit longer, but I had no excuse for not knowing about Black Psychology. I wish I could go back in time and educate myself.

We hire in domains like cognitive, or developmental, or neuro, or clinical, etc. I think cognitive is fairly deep and wide in terms of its scholarship. Black Psychology is deeper and wider, and it has had less time to explore the territory than other domains. This is just to say what should go without saying, Black Psychology is a foundational field and unique domain of inquiry in psychology. It's true because Black psychologists made Black Psychology. And, the more I realize what I'm missing, the more I can't bear the thought of students at Brooklyn College not learning from Black Psychologists about Black Psychology. It would be like not having a cognitive course, which would make our program a laughing stock. Oh wait, we already are a laughing stock.

I blame myself for missing an entire field in Psychology. I could also blame all of the places where I trained for not ever teaching me about black psychology. Maybe I wasn't listening. But, I've been around a few blocks in terms of psych departments, and it's shameful how widespread the lack of recognition and support and awareness there is for Black Psychology. That's an institutional failure. Are you working in a failed intitution right now? I am.

I could say similar arguments for hiring in other domains in psychology where we don't have courses, there's lots of psychology out there. But, I'm not an advocate for all psychology. Actually, more and more I find myself advocating against parts of psychology. It's almost like there is something wrong with part of psychology. No shit.

Black Psychology has been the premier psychology dealing with white racism in Psychology, which HELLO, is most of psychology. I am beginning to learn of the extreme depths and pervasiveness of white racism and eugenics in psychology. Deconstructing white racist structures in psychology is part of the legacy and black psychology scholarship. Students at Brooklyn College need to learn about this.

Black Psychology has reconstructed psychology and constructed it's own psychology. I'm still very new to these wings of Black psychology, but I know enough to know that our students need to learn about them ASAP. Also, our faculty need more black psychologist colleagues who are doing cutting edge research that informs, challenges us, and helps our community.

OK, so what am I going to do about it?

1. Advocate in my department for creating a line in the domain of black psychology
2. Don't stop until the line is approved by the administration
3. Learn how to do the above until it happens
4. Maybe use this page as a space to rewrite arguments, and figure stuff out
5. Convince individual faculty that this is a good idea, so that they will also advocate for this line. The more the merrier, the easier to get the line request through the appointments committee.
6. Discuss this line request with our diversity committee, figure out how they can help
7. Organize help for writing the line request sent to the administration so that it is as convincing as possible in terms of what the administration is looking for
8. Learn from black psychologists who have begun faculty positions at institutions where black psychology is new about what they need.
9. Advocate for those things
10. Get courses on black psychology on the books even if we don't have anyone to teach them yet.

## References




