---
title: "Looking back on a few years of OER development"
author: "Matt Crump"
date: "Last edited: `r format(Sys.time(), '%d %B, %Y')`"
twitter:
  card_description: "Some thoughts on developing open educational resources while at Brooklyn College of CUNY"
  card_img: "https://crumplab.github.io/blogposts/11_3_20_OER/img/OER.png"
bibliography: refs.bib
csl: web/apa.csl
output: 
  html_document:
    template: web/template.html
    toc: true
    toc_float: true
    collapsed: false
    number_sections: false
    toc_depth: 3
    theme: yeti
    highlight: kate
    css: web/crump_basic.css
    includes:
      in_header: [web/header.html,../../g_analytics.html]
    md_extensions: -autolink_bare_uris
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

---

This blog post is currently in a provisional state of being written, and when it's more or less finished, I'll take this message off.

---

I was recently prompted to look at an old blog post from two years about my experience with developing open educational resources (OERs), and it seemed like time to make an updated post.

I first came across OERs teaching at Brooklyn College, sometime around 2017-ish. It turns out I had been developing curriculum in the spirit of open education for a while, I just didn't have a name for it, and I didn't know that there was a larger, more organized movement of educators dedicated to creating open/free and 
remixable/editable educational resources. Briefly, OERs come in all shapes and sizes and are often shared on a [creative commons license](https://creativecommons.org/licenses/) that allows other people to remix, edit, and reuse the original resource.

Back in 2017, I discovered that the Brooklyn College library had small grants to incentivize OER adoption among the faculty. One of the goals was to increase the number of zero-textbook cost courses for our students. I was teaching a research methods course for undergraduates in psychology and wondered if there was an OER option for my course. I did a quick search and quickly found an OER textbook suitable for my needs. I decided to give the OER thing a try. An appealing option was that I could copy the whole thing, edit it according to my needs, and share it back out again...

Also around the same time I was learning more and more about [R markdown](https://rmarkdown.rstudio.com), a wonderful notebook style coding syntax that affords a wide range of compilation options, including pdfs, websites, and web-books. 


## Round one: Research Methods

I put these two interests together and created my first OER. The result was [Research Methods for Psychology](https://crumplab.github.io/ResearchMethods/). This textbook was originally written by Paul C. Price, but was subsequently revised and remixed by several authors (Rajiv Jhangiani, I-Chant A. Chiang, Dana C. Leighton). My version of the textbook was a fourth or fifth iteration. For my first foray, I didn't change much of the actual content of the book. Instead, I converted the .pdf into an R Markdown source document, and then compiled the textbook into a web-book using the amazingly amazing [bookdown package](https://bookdown.org). All of the source code is in a Github repository <https://github.com/CrumpLab/ResearchMethods>, so anyone copy it, edit it, and serve their own version of the textbook. I taught the class a couple times with this free OER textbook and it worked out pretty well. I think a couple colleagues might have used this too. So, at the end of the day, this saved students some money, and delivered comparable content, not bad for a first go.

## Round two: Statistics

I guess I caught some kind of OER bug, because in around 2018 I thought it would be a good idea to create an OER textbook and associated resources for our undergraduate introductory statistics course in Psychology. I hadn't taught statistics at Brooklyn College up to that point, but I had my mind set on both teaching statistics and creating lab content to give students some exposure to R, a free and open source programming language that is widely used for data-analysis.

Fortunately, Brooklyn College again supported this initiative with a small grant. And, a small team of colleagues and I developed a suite of OER material that we all now use for teaching statistics.

At the time of developing the statistics textbook I had become more aware of the larger OER landscape, and it was a  veritable buffet of free undergraduate statistics textbooks. I had hoped to slam together various chapters from different books and make a passable textbook, and I could have easily done that. There is so much great content out there. At the end of the day I had too many feelings, so decided to write a textbook myself. However, I got a huge headstart from Danielle Navarro, and pulled a couple chapters from her increasingly well-known modern classic and fantastic book, [Learning statistics with R]( https://learningstatisticswithr.com).

At the end of summer 2018, we had created a whole bunch of OER content for statistics. For example, there is the textbook [Answering Questions with Data](https://crumplab.github.io/statistics/), which was written in R Markdown and hosted on Github as a bookdown book. We also made a [lab manual](https://crumplab.github.io/statisticsLab/) that has loads of practical exercises, and has versions for students learning R, SPSS, Excel, and Jamovi. 

In keeping with my obsession in using R Markdown to create content, I also created a [course website](https://crumplab.github.io/psyc3400/) and [slide decks](https://crumplab.github.io/psyc3400/Lectures.html) for all of my lectures; and these are all creative commons licensed. The source code for the textbook, lab manual, course website, and slides are all on github repositories, and anybody can fork the repos, remix, re-use, edit, and share their own versions that are suitable for their needs. 

It's now been almost three years since those materials were made. I was on sabbatical for one of those years, so haven't gotten back to the task of revising and improving things. But, it seems that the repos have been forked a bunch of times, and once in a while I'll hear that someone has adopted the materials and found them useful. I even think my students appreciated the free textbook, and hopefully, occasionally, my approach to teaching statistics.

## Round 3: Right now





