---
title: "Psychology and Eugenics connections"
author: "Matt Crump"
date: "Last edited: `r format(Sys.time(), '%d %B, %Y')`"
twitter:
  card_description: "Making notes and connecting dots about the pervasiveness of eugenics ideology among psychologists"
  card_img: "https://crumplab.github.io/blogposts/7_13_20_PsychEugenics/img/eugenics.jpg"
bibliography: refs.bib
csl: web/apa.csl
output: 
  html_document:
    template: web/template.html
    toc: true
    toc_float: true
    collapsed: false
    number_sections: false
    toc_depth: 3
    theme: yeti
    highlight: kate
    css: web/crump_basic.css
    includes:
      in_header: web/header.html
    md_extensions: -autolink_bare_uris
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

---

I'm working through the task of learning about influences of eugenics on psychology and society. As a part of this, I'm documenting the eugenics views held by many psychologists, as well as connections between psychologists and eugenics. I will keep updating this page as I document the connections. There are many connections, it will take some time. So far, this is an emerging disorganized collection of factoids.

A major overarching goal of compiling and documenting connections between psychology and eugenics is to better understand how strucutural eugenics and racism in the discipline of Psychology has shaped and continues to shape the field, both in terms of the questions it asks, and who gets to ask them.

## Sir Francis Galton

  - Inventor of eugenics
  - effectively initiates individual differences psychology, for the purposes of eugenics
  - Obviously much more can be said about Galton...
  
## Karl Pearson

  - Eminent Statistician. Inventor of many common statistics (e.g., Pearson's R)
  - Galton appointed Pearson as the first Director of his Eugenics Laboratory at University College London, this is still in use today
  - The depths of Pearson's eugenics are apparent in his length effort to measure jewish children like animals, and apply his statistical tools to eliminating "bad" jews from immigrated to the UK [@pearsonProblemAlienImmigration1925]. This reference is part I of III, and continues for several hundred pages. To my mind, this work is obviously used as a blueprint by the Nazi's.
  
## Ronald Fisher

 - fill in refs 
  
## Alexander Graham Bell & Bell Labs

  - Notable figure who was a prominent eugenicist
  - Bell labs became central to the development of many communication technologies, and numerous important figures in the emerging discipline of cognitive science worked at Bell Labs. 
  - I need to look more into the culture of eugenics at Bell labs, but perhaps not surprisingly there appears to be on, e.g.,  [https://en.wikipedia.org/wiki/William_Shockley](https://en.wikipedia.org/wiki/William_Shockley)
    
    
## American Psychological Presidents
 
 - @yakushkoEugenicsItsEvolution2019 writes that 31 APA presidents between 1892 -1947 were affiliated with or leaders in eugenics movements. Need to fill this list out (also it extends past 1947 as we will see)
 
### 1892 Granville Stanley Hall 
 
 - Noted as joining as new active member of the Eugenics Record Office in the Eugenical News
   
### 1893 George Trumball Ladd
 
 - his presidential address is published in the first issue and volume of Psychological Review. He does not use the word eugenics, but appears to dogwhistle to the eugenicists in the room in his closing paragraphs about improving society. Also, many of the authors in the first issue of Psyc Review, were eugenicists
   
### 1895 James McKeen Cattell

  - [wikipedia page](https://en.wikipedia.org/wiki/James_McKeen_Cattell)
  - Founded Psychological Review, as journal of APA
  - bought Science, editor for 50 years
  - APA president 1895
  - Eugenicist, attempted to development intelligence tests that didn't quite work out, presumably for the purposes of eugenics. This is a nice example of efforts that pre-date Binet's IQ test to develop "scientific" mental tests for the purposes of eugenics.
    - Note to self to locate if Cattell expresses his eugenics in writing.

### 1897 James Mark Baldwin

 - The mental development in the child and race: methods ands processes [@baldwinMentalDevelopmentChild1900]

### 1898 Hugo Munsterberg

 - Is written up in the eugenical news as a fine speciman, "Sensorium of a Psychologist", Eugenical News, Vol VII, No. 10, October 1922
    
### 1899 John Dewey

 - Keeps coming up in the context of eugenics and education...need to learn more
 - @yakushkoEugenicsItsEvolution2019 points out that Dewey & Gordon Allport were anti-eugenics.
    
### 1900 Joseph Jastrow

  - Had an interest in psychic phenomena
  - [@jonesHistoryOverviewPsychometrics2006], describe how Jastrow was a proponent of Galton in the US, established a lab in Chicago alongside Franz Boas (an anthropologist who advocated against eugenics, @boasEugenics1916). 
  - Wrote on the science of "human quality" [@jastrowCharacterTemperament1921]
  - listed in eugenical news as an active researcher
    
### 1901 Josiah Royce

  - Philosopher (American Idealism)
  - At harvard, apparently convinced Robert Yerkes to combine his interests and do psychology
  - Gets written up in the eugenical news at least once
  - haven't spent time to look into his writing (or lack thereof on eugenics)

### 1902 Edmund Clark Sanford

 - Supervised Lewis Terman, who created Stanford-Binet IQ test
 - Acknowledged as helping out with a dissertation on "The Psychology of Superior Children" [@richards-nashPsychologySuperiorChildren1924]

### 1903 William Lowe Bryan

  - did some work on aquiring telegraph skill, touched all the bases of modern work on transcription skill.
  - President of the Indiana Society for Mental Hygiene (elected 1919)

### 1904 William James

  - doesn't appear to discuss eugenics?
    
### 1905 Mary Whiton Calkins

  - First Female APA president!
  - Student of William James
  - has some writing on ethics, espouses progressive views [@calkinsGoodManGood1918]

### 1906  James Rowland Angell

  - Also eventual president of Yale and eugenics proponent
  - Supervisor of J. B. Watson
  - See @doyleMeasuringProblemsHuman2014 on eugenics in Psychology at Yale
  - Did early mental chronometry research
  - Expressed some of his racialized views of intelligence in @angellEvolutionIntelligence1922

### 1907  Henry Rutgers Marshall

  - interested in aesthetics

### 1908  George Malcolm Stratton

  - From wikipedia, Stratton served in the Army during World War I, developing psychological tests to select airmen for Army aviation
  - Did prism experiments (upside-down looking)
  - published lots of different esoteric things, on feats of memory, to anger in cattle, to how cattle get excited by blood
  - Some discussion of Stratton's role in driving research effort into African Americans [@yudellRaceUnmaskedBiology2014].

### 1909  Charles Hubbard Judd

  -  educational psychologist

### 1910  Walter Bowers Pillsbury

  - from [http://www.cyberus.ca/~pballan/Pillfina.htm](http://www.cyberus.ca/~pballan/Pillfina.htm): This personal brush with political prejudice did not change Pillsbury's official scientific stance on race and mental degeneracy. His Education as the Psychologist Sees It (1920), for instance, was part of a successful nationwide postwar marketing campaign advocating the use of new group "mental testing" techniques in American schools. Here, Pillsbury uncritically combined past eugenic twin-studies with the new "Army Alpha and Beta" intelligence testing data. Surprisingly, his personal conclusion after thirty-three years of teaching is "that one can never produce intelligence by education, that one must begin much farther back in actually insuring the birth of intelligent people" (p. 46). [p. 525] At this time, however, Pillsbury was just one of many psychologists who accepted such notions (e.g., R. M. Yerkes, Psychological Examination in the United States Army [1921]; W. S. Hunter, General Psychology [1919]; R. S. Woodworth, Psychology [1921]).

### 1911  Carl Emil Seashore

  - Seashore, music and eugenics: [http://www.brooklyn.cuny.edu/web/academics/centers/hitchcock/publications/amr/v48-2/devaney.php](http://www.brooklyn.cuny.edu/web/academics/centers/hitchcock/publications/amr/v48-2/devaney.php)
  - Seashore wrote extensively on eugenics and euthenics
  - Member of Advisory Council: International commission on eugenics, Eugenics committee of the United States of America

### 1912 Edward Lee Thorndike

  - wrote extensively on eugenics
    - @thorndikeHumanNatureSocial1940
    - @thorndikeEugenicsSpecialReference1913
  - Member of Advisory Council: International commission on eugenics, Eugenics committee of the United States of America

### 1913 Howard Crosby Warren

  - SEP society gives the HC Warren medal every year
  - Listed as a new active member of Eugenics Research Association in Eugenical News

### 1914 Robert Sessions Woodworth

  - obit appears in the Eugenics Review [@welfordCurrentPsychologicalIssues1961]
  - see discussion on Woodworth's eugenics at Columbia [@rupertRaceScienceColumbia2019]
  - Member of Advisory Council: International commission on eugenics, Eugenics committee of the United States of America
  
### 1915 John Broadus Watson

 - The famous behaviorist
 - Listed as a eugenics researchers in the Eugenical News
 - Angell was his advisor
 
### 1916 Raymond Dodge

 - From Doyle, "Dodge was also pleased that his research in human variability and psycho- psychology was so valued by the prospective Institute. While Dodge never publicly identified as a eugenicist, he applauded the National Origins Act of 1924 and was a proponent of applying psychological research to public discourse on selective immigration.93"
 - did some IQ testing in the war
 
 
### 1917  Robert Mearns Yerkes

  - Implemented the Alpha and Beta IQ tests on the Army (1.5 - 2 million army men tested).
  - Pretty clear from his report [@yerkesEugenicBearingMeasurements1923], that he wanted the tests to validate whites becoming officers, and "morons" and immigrants and blacks to be fodder for the front line, or otherwise eliminated
  - Member of Advisory Council: International commission on eugenics, Eugenics committee of the United States of America
  
### 1918 John Wallace Baird

  - Canadian psychologist, connection to eugenics? 

### 1919 Walter Dill Scott

  - intelligence tester, early IO psychology, e.g., applying scientific selection to salesmen @scottScientificSelectionSalesmen1915
  - wikipedia suggests Scott followed in the Galton eugenics tradition, maintained similar elitist views
  
### 1920 Shepard Ivory Franz

  - went to school with Thorndike, studied under Cattell
  - wrote "Psychology as life work" with Thorndike and others, @dodgePsychologyLifeWork1923
  - Haven't found specific eugenic writings from Franz
  
### 1921 Margaret Floy Washburn
  
  - first woman to get a Ph.D. in Pysch
  - studied under Cattell & Titchener, did comparative cognitive

### 1922 Knight Dunlap

  - Author of "Personal Beauty and Racial Betterment" @dunlapPersonalBeautyRacial1920
  - Member of Advisory Council: International commission on eugenics, Eugenics committee of the United States of America
  
### 1923 Lewis Terman

 - APA president 1923
 - Adapts Alfred Binet's IQ test to English at Stanford, creating the Standford-Binet IQ test.
 - See his eugenic views on feeble-mindedness in school children in California [@terman1917feeble]
 - Member of Advisory Council: International commission on eugenics, Eugenics committee of the United States of America
 
### 1924 Granville Stanley Hall (2nd time)

 - see above
 
### 1925 Madison Bentley

 - author of Mental Inheritance (1909) [https://en.wikisource.org/wiki/Popular_Science_Monthly/Volume_75/November_1909/Mental_Inheritance](https://en.wikisource.org/wiki/Popular_Science_Monthly/Volume_75/November_1909/Mental_Inheritance)
 
### 1926  Harvey A. Carr

 - Carr, H. A., & Kingsbury, F. A. (1938). The concept of traits. Psychological Review, 45(6), @497–524. https://doi.org/10.1037/h0063048
 - Carr, H. A., & Kingsbury, F. A. (1938). The concept of ability. Psychological Review, 45(5), 354–376. https://doi.org/10.1037/h0055419
 - Haven't found specific eugenic writing
 
### 1927 Harry Levi Hollingworth

 -  advocates for eugenics in the book "Vocational Psychology" @hollingworthVocationalPsychologyIts1916
 
### 1928  Edwin Garrigues Boring

 - credited with founding the history of psychology discipline
 - worked with Yerkes doing IQ testing in the military
 - Eugenics views unclear, seems to not discuss the topic so much when he writes his histories
 
### 1929 Karl Lashley

 - detailed analysis of Lashley's racism and hereditarianism @weidmanConstructingScientificPsychology1999
 
### 1930 Herbert Sidney Langfeld

 - writes on eugenics related issues here @langfeldIIHeredityExperience1949, but focuses more on the nature/nuture debate, and seems to take a neutral side on eugenics, which references in terms of "political" takes on the issues. 
 
### 1931 Walther Samuel Hunter

 - From wikipedia, this is a perfect description of accidental eugenics, "Hunter served in the military for sixteen months during World War I. He was the chief psychological examiner in three army camps.[2] During that time he compiled bar graphs with E.S. Jones that showed the predictive value of group psychological tests.[3] His work persuaded government officials to continue the testing program, which ultimately led military officials to order the recording of data on the national origins of the troops tested.[3] The data collected was used in a way that Hunter did not approve; combining the psychological test scores with the location of where the individual grew up supported the notion of Nordic superiority, which was not his intention.[3]"
 - 
  
## Henry Goddard

 - Goddard argued for classifying “feeble-minded” people into classes by IQ, e.g., idiots ~ 20, Imbeciles ~ 40, Morons ~ 70, see Goddard’s “Who is a Moron?” [@goddardWhoMoron1927]. 
 - The fear was that morons are basically normal competent people who are able to hide in society, but they will also destroy the human race if they are allowed to breed. The only way to discover morons was to IQ test them, and then employ eugenics polices to prevent morons from breeding.
 - Member of Advisory Council: International commission on eugenics, Eugenics committee of the United States of America
 
## Claude Shannon

 - completed his masters thesis at Cold Springs Harbor Laboratory (Eugenics Record Office) [https://liorpachter.wordpress.com/2013/11/05/claude-shannon-population-geneticist/](https://liorpachter.wordpress.com/2013/11/05/claude-shannon-population-geneticist/)
 - switched to invent information theory aftwerward

## George A. Miller
 
 - wrote on eugenics in Daedalus, @millerPsychologicalPerspectivesYear1967

## Abraham Maslow

 - Posthumous journal notes suggest his humanism was rooted in eugenics
 - @maslowJournalsAbrahamMaslow1982






## References




