---
title: "Reading the Journal of Black Psychology"
author: "Matt Crump"
date: "Last edited: `r format(Sys.time(), '%d %B, %Y')`"
twitter:
  card_description: "I'm reading the Journal of Black Psychology from the beginning, and writing about it here."
  card_img: "https://crumplab.github.io/blogposts/7_2_20_JBP/JBP.png"
bibliography: refs.bib
csl: web/apa.csl
output: 
  html_document:
    template: web/template.html
    toc: true
    toc_float: true
    collapsed: false
    number_sections: false
    toc_depth: 4
    theme: yeti
    highlight: kate
    css: web/crump_basic.css
    includes:
      in_header: web/header.html
    md_extensions: -autolink_bare_uris
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

---

[The Association of Black Psychology](http://www.abpsi.org) has been publishing the [Journal of Black Psychology](https://journals.sagepub.com/home/jbp) since 1974. I just learned about it. So, I'm reading it, because that's what you do when you find out that you missed an entire foundational field in psychology.

I'm a cognitive psychologist who spends a large part of my research time considering how cognition in general is supported by computations of learning and memory processes. I'm also interested in psychology more broadly: how it fits together as a discipline, and how the institutions of psychology work, how psychology influences society, etc. 

My impression  of my own field, cognition, is that it is highly fragmented. Theree's lots of veryone doing their own thing. There is no unified field theory of anything. Wondering about the "point" of things in cognitive psychology has sucked years of my life away. I guess I enjoy it, and like many other disciplines, perhaps struggling with the point is part of the point. Points don't come for free.

I still think of myself as a NKOTB, [hanging tough](https://www.youtube.com/watch?v=By86PcLufOU) in psychology, oh, oh, oh, oh, oh. In my case, when you grow up in a northern Canadian small town, and then start grad school in 2001 (checks CV), you enter into a field that has been doing its thing without you for a long time. And, your job is to figure out a small part of that landscape, dig a new hole somewhere, and convince everyone else that no one looked in the hole before. If you do a good of this, you can dig into that hole for the rest of your life and never have to leave. I've been digging holes. It's not that I haven't been wondering why. I come up with lots of reasons to dig the holes I dig. 

In any case, to wrap this up. I was recently appalled by the Psych Science publishing the now retracted racist IQ paper. I haven't been paying attention to the scope of racism in my own discipline. By tugging at the thread of the history of IQ research, which I also mostly didn't learn about in my training, I've been horrified to discover just how much eugenics played a role in founding and propagating psychology [@yakushkoEugenicsItsEvolution2019]. 

I'm in the process of climbing out of my research hole to learn about the racist and eugenicist ideologies that have dug the rabbit holes of psychology. As a part of this work, I found out the Journal of Black Psychology has been dismantling these issues from their inception, so I'm here to learn from the experts.

I've already done some reading and skimming through the journal. So, even though I know this work will inform me about structural racism and eugenics in psychology, I also know it will inform me about many other issues that I wasn't thinking so much about. The papers I have read so far are building towers of perspective over the holes of psychology. I'm excited to read more, I need to start keeping notes:

---


@williamsHistoryAssociationBlack1974

---


## References




