---
title: "Teaching with multiple warp zones: Engagement and assignment choice"
description: "*May 18th, 2022* - Some thoughts on how I implemented loads of assignment choice in my intro to cognition course this semester. "
author: "Matt Crump"
date: '2022-05-17 `r paste("Last knit: ", lubridate::today())`'
opengraph:
  image: 
    src: ""
  twitter:
    card: summary_large_image
    creator: "@MattCrumpLab"
    site: "@MattCrumpLab"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Grading with multiple warp zones}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


I lack positive emotions toward the process of grading in my courses. I have lots of positive emotions for my students. Grading stresses people out. I'll save my thoughts about grading in general for another day. 

What I really want to talk about are decisions I made to increase assignment choices in the course I just finished this semester. I flooded the gates with tons of ways to get an A in the course. It worked, I had fun, I think my students had fun and they got a lot of As. More important, my students engaged in the material in more ways than they normally would have.

I'll say a little bit about my course and then talk about how I implemented lots of assignment choice this semester.

## A bit of background

This spring 2022, I taught an introductory survey course on cognitive psychology. I've been at Brooklyn College for over a decade and haven't taught my core area very often. Since summer 2021, I've been making up for lost time and decided to develop a [suite of open educational resources for introductory cognition](https://www.crumplab.com/cognition/). I ran the course for the first time last semester. The modality was synchronous online, so students joined me every week for class lectures. I intended to have a textbook chapter for each week of the course, but I didn't get that far in writing the textbook so we ran out of textbook chapters after nine weeks (note to self, that I need to [finish the book](https://www.crumplab.com/cognition/textbook)).

In any case, the format for fall 2021 was fairly standard. I had weekly multiple choice quizzes that I posted on blackboard. I had two midterms and final exam. I gave students a few ways to get extra credit. And, I offered some optional writing assignments for students that wanted to dig into the material a little bit more.

The class went off the rails in the middle of the semester. That's a story for another day, but let's just say there an extraordinary amount of unapproved student collaboration occurred. I also learned that I would be teaching the same course again in spring 22 but this time in an asynchronous online format. I knew I wanted to create more interesting assignments for the asynchronous version of the course. So, made up a bunch of assignments, and allowed my students in the fall to make up points in the course they might have a lost for their unapproved collaborations.

## Planning for the asynchronous online modality

At Brooklyn College we don't teach during the January intercession, so I had a bunch of time to plan out how I would convert the course from synchronous online to asynchronous online. Ultimately, this involved creating a ton of content, which was a huge amount of effort. And, I put all of that content into "learning modules" for each week of the course. All of the [learning modules are on the course website](https://www.crumplab.com/cognition/articles/modules/L0_Getting_Started.html), and freely available as an open educational resource.

I structured each learning module into three parts: Read, Watch/Listen, and Engage. The reading section usually linked to a textbook chapter, or any additional readings I wanted to assign. The watch/listen section contained mini-lectures that I recorded and posted YouTube (this part took so much time every week). The engage section contained quizzes and assignments that student could complete each week. 

This was my first time teaching an asynchronous online course. In 2020-2021 I happen to take a year-long ACUE online teaching certificate course, so I had seen lots of ways to do courses online. 

Add some general goals for the asynchronous format, which meant students would be largely on their own to complete content across the semester.

## Multiple Warp Zones

Given the asynchronous format, I wanted to give students every opportunity to do well in the course. I also wanted to dream up as many ways as I could think of to to offer students meaningful ways to engage with the course material. 









