---
title: "Resources for Learning R"
author: "Matt Crump"
date: "`r format(Sys.time(), '%d %B, %Y')`"
twitter: "https://twitter.com/MattCrump_"
github: "https://github.com/CrumpLab"
website: "https://crumplab.gihub.io"
bibliography: refs.bib
csl: web/apa.csl
output: 
  html_document:
    template: web/template.html
    toc: true
    toc_float: true
    collapsed: false
    code_folding: show
    number_sections: false
    toc_depth: 4
    theme: yeti
    highlight: kate
    css: web/crump_basic.css
    includes:
      in_header: web/header.html
    md_extensions: -autolink_bare_uris
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

---

There are so many good and free resources for learning to code these days. I need a place to keep a list of these resources so I can more easily share them (and remember them myself). I'll update this and add more as I come across them.

## Crump's Resources

I have an interest in teaching R & programming skills in general, so have developed various materials for courses I teach. 

---

### Programming for Psychologists

**Website**: [https://crumplab.github.io/programmingforpsych/](https://crumplab.github.io/programmingforpsych/)

This OER book needs an update...but it covers basic programming in R and couple other languages (LIVECODE and Javascript). This is really more of a collection of lecture notes I used in a few classes I taught on applying programming skills to creating computerized experiments in Psychology, and for data analysis. 

I'm a big fan of having concrete problems to solve as a way to learn programming. It can be difficult to learn about a bunch of new abstract concepts, and then have no idea how to apply them. Some basic programming concepts include variables, logic statements, looping, and writing functions and algorithms that "do" something. The first few chapters of this book cover some of these concepts, and then present a series of [programming challenges](https://crumplab.github.io/programmingforpsych/programming-challenges-i-learning-the-fundamentals.html), which are relatively concrete problems for students to solve by themselves. This was inspired by the [https://projecteuler.net](https://projecteuler.net) website, where you can sign up, and solve programming challenges and then see other solutions (after you have gotten the correct answer). 

---

### Answering Questions with Data (OER Textbook for Undergraduate Psych Statistics)

**Website**: [https://crumplab.github.io/statistics/](https://crumplab.github.io/statistics/)

This is a free undergrad statistics textbook I wrote in 2018, and have used for intro stats at Brookyln College. The book itself was written in R, using the bookdown package. R concepts are peppered throughout, but it is really more about statistics...This is a reminder to me that I should probably revise this at some point to add more R exmamples (as that's what I'm teaching). At the moment, most of the R content is relayed in the accompanying Lab manual.

---

### Answering Questions with Data: The lab manual 

**Website**: [https://crumplab.github.io/statisticsLab/](https://crumplab.github.io/statisticsLab/)

This is the lab manual I use in my undergrad psych statistics course. In general, each lab has open data from psychology experiments, and R code to run various kinds of statistical analyses appropriate to the data. It's focused on tidyverse style analysis. 

---

### Using R for reproducible research

**Website**: [https://crumplab.github.io/psyc7709/](https://crumplab.github.io/psyc7709/)

I recently taught (Spring 2019) a graduate course for using R for reproducible research. This website contains the course materials I developed. The weekly assignments and content are described on the schedule page.

---

## More Great Resources for Learning R

In no particular order, and covering a range of things from learning to program, statistics, more advanced R things, cheatsheets, and general tips and things to know about.

---

### R For Psychological Science

**Website**: [https://psyr.org](https://psyr.org)

Danielle Navarro's excellent notes and resources for learning to program in R

---

### Learning Statistics with R

**Website**: [https://learningstatisticswithr.com](https://learningstatisticswithr.com)

Danielle Navarro's fantastic undergraduate statisics textbook that also teaches R.

---

### Statistical Thinking for the 21st Century

**Website**: [http://statsthinking21.org](http://statsthinking21.org)

Russell Poldrack's fantastic undergraduate statisics textbook that also teaches R.

---

### swirl

**Website**: [https://swirlstats.com](https://swirlstats.com)

Swirl is an R package that teaches R concepts inside R.

---

### R Cheat sheets

**Website**: [https://www.rstudio.com/resources/cheatsheets/](https://www.rstudio.com/resources/cheatsheets/)

R-studio maintains several cheatsheets that are visually appealing, and packed with loads of helpful tips and reminders.

---

### Modern Dive

**Website**: [https://moderndive.com/index.html](https://moderndive.com/index.html)

Another great stats and R book by Chester Ismay and Albert Y. Kim.

---

### PsyTeachR

**Website**: [https://psyteachr.github.io](https://psyteachr.github.io)

Loads of R course material and books from the team at University of Glasgow.

---

### A Language, not a letter: Learning statistics in R

**Website**: [https://ademos.people.uic.edu/index.html](https://ademos.people.uic.edu/index.html)

Another great intro to R programming and statistics (by many contributing authors).

---

### Software Carpentry R

**Website**: [http://swcarpentry.github.io/r-novice-inflammation/](http://swcarpentry.github.io/r-novice-inflammation/)

Another fantastic introduction to basic coding and data analysis in R.

---

## More Advanced R resources

Here are a few resources I've found very helpful for levelling up in terms of my R skills.

---

### Advanced R

**Website**: [https://adv-r.hadley.nz](https://adv-r.hadley.nz)

Hadley Wickham's second edition of Advanced R. If you are past the novice stage, or want to see what more advanced things look like in R, this book is for you.

---

### R Packages

**Website**: [http://r-pkgs.had.co.nz](http://r-pkgs.had.co.nz)

Hadley Wickham's book on making R packages, an excellent resource.

---

### R Markdown: The definitive guide

**Website**: [https://bookdown.org/yihui/rmarkdown/](https://bookdown.org/yihui/rmarkdown/)

This book saves my life on a routine basis, thank you to the authors: Yihui Xie, J. J. Allaire, Garrett Grolemund. If you want to supercharge your R markdown skills to make reproducible documents, websites, books, slides, and more, check this out.

---

### Pimp my RMD: a few tips for R Markdown

**Website**: [https://holtzy.github.io/Pimp-my-rmd/](https://holtzy.github.io/Pimp-my-rmd/)

More than a few good tips for .rmd documents from Yan Holtz.

---

### Happy Git and GitHub for the useR

**Website**: [https://happygitwithr.com](https://happygitwithr.com)

Wonderful resource for getting started with Git and R (by Jenny Bryan, the STAT 545 TAs, Jim Hester).

---

### More books from R-studio

**Website**: [https://www.rstudio.com/resources/training/books/](https://www.rstudio.com/resources/training/books/)

---

### More Bookdown Books

**Website**: [https://bookdown.org](https://bookdown.org)

A whole whack of books written in Bookdown (an R package for writing books)

---

### R-studio Community

**Website**: [https://community.rstudio.com](https://community.rstudio.com)

A message board to post and talk about R and R-studio.

---

### R-studio Cloud

**Website**: [https://rstudio.cloud](https://rstudio.cloud)

A free service to run R-studio in your web-browser. Can be very helpful for teaching and using R (no need to download anything, just sign up and start using R-studio)

---

### Paul Vanderlacken's list of R resources

**Website**: [https://paulvanderlaken.com/2017/08/10/r-resources-cheatsheets-tutorials-books/](https://paulvanderlaken.com/2017/08/10/r-resources-cheatsheets-tutorials-books/)

This is a huge list of great resources (I suppose I could have just linked to this amazing list, and have been done with this post.)

---

### TidyTuesday

**Website**: [https://github.com/rfordatascience/tidytuesday](https://github.com/rfordatascience/tidytuesday)

Learn R, graphing, and data-analysis by participating in #TidyTuesday. Every Tuesday a new data set is released, and people from all over load the data into R and produce visualizations (and share code). Most of the action is on Twitter.

---

### R4DS R for data science online learning community

**Website**: [https://www.rfordatasci.com](https://www.rfordatasci.com)
**Book**: [https://r4ds.had.co.nz](https://r4ds.had.co.nz)

R4DS is an online learning community (using slack) for learning data science with R. Maybe I should join! Looks pretty neat.

---

### r-exercises.com

**Website**: [https://www.r-exercises.com/start-here-to-learn-r/](https://www.r-exercises.com/start-here-to-learn-r/)

Lots of exercises to learn R.

---





## R Packages worth knowing about

Some R packages I use all the time.

1. [tidyverse](https://www.tidyverse.org) - A whole bunch of useful packages
2. [ggplot2](https://ggplot2.tidyverse.org) - for graphing, part of the tidyverse
3. [dplyr](https://dplyr.tidyverse.org) - for data-wrangling, part of the tidyverse
4. [data.table](https://cran.r-project.org/web/packages/data.table/vignettes/datatable-intro.html) - for data-wrangling
5. [usethis](https://usethis.r-lib.org) - helpful for development
6. [roxygen2](https://cran.r-project.org/web/packages/roxygen2/vignettes/roxygen2.html) - helpful for writing packages
7. [bookdown](https://bookdown.org) - writing books
8. [pkgdown](https://pkgdown.r-lib.org) - writing packages
9. [devtools](https://www.rstudio.com/products/rpackages/devtools/) - helpful for development
10. [gganimate](https://gganimate.com) - animate ggplot graphs
11. [tm](https://www.rdocumentation.org/packages/tm/versions/0.7-6) - text mining and NLP stuff
12. [papaja](https://crsh.github.io/papaja_man/) - write APA manuscripts in R markdown
13. [plotly](https://plotly-r.com) - another graphing package, with interactive JavaScript graphs
14. [nomnoml](https://github.com/javierluraschi/nomnoml) - make cool box arrow flow charts
15. [Rcpp](http://adv-r.had.co.nz/Rcpp.html) - run C++ code in R when you have the need for speed





